imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    default_locale:  %locale%
    translator:      { fallback: en }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_all_services: false

# SonataAdminBundle
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    title:      MediaWatch
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            mediawatch_common:
                label: Common
                items: ~
            mediawatch_feed:
                label: Feed
                items: ~    
            mediawatch_media:
                label: Media
                items: ~ 
            mediawatch_user:
                label: User
                items: ~
    security:
        handler: sonata.admin.security.handler.role
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER

services:
   mediawatch.common.admin.language:
      class: Mediawatch\AdminBundle\Admin\LanguageAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_common, label: Language }
      arguments: [null, Mediawatch\MediaBundle\Entity\Language, null] 
   mediawatch.common.admin.languagecategory:
      class: Mediawatch\AdminBundle\Admin\LanguageCategoryAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
      arguments: [null, Mediawatch\MediaBundle\Entity\LanguageCategory, null] 
   mediawatch.common.admin.medialanguagecategory:
      class: Mediawatch\AdminBundle\Admin\MediaLanguageCategoryAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
      arguments: [null, Mediawatch\MediaBundle\Entity\MediaLanguageCategory, null] 
   mediawatch.common.admin.mediaspeaker:
      class: Mediawatch\AdminBundle\Admin\MediaSpeakerAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
      arguments: [null, Mediawatch\MediaBundle\Entity\MediaSpeaker, null]
   mediawatch.common.admin.mediatag:
      class: Mediawatch\AdminBundle\Admin\MediaTagAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
      arguments: [null, Mediawatch\MediaBundle\Entity\MediaTag, null]    
   mediawatch.common.admin.category:
      class: Mediawatch\AdminBundle\Admin\CategoryAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_common, label: Category }
      arguments: [null, Mediawatch\MediaBundle\Entity\Category, null]
   mediawatch.common.admin.tag:
      class: Mediawatch\AdminBundle\Admin\TagAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_common, label: Tag }
      arguments: [null, Mediawatch\MediaBundle\Entity\Tag, null]
   mediawatch.common.admin.mediatype:
      class: Mediawatch\AdminBundle\Admin\MediatypeAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_common, label: Mediatype }
      arguments: [null, Mediawatch\MediaBundle\Entity\Mediatype, null]
   mediawatch.common.admin.page:
      class: Mediawatch\AdminBundle\Admin\PageAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_common, label: Page }
      arguments: [null, Mediawatch\PageBundle\Entity\Page, null] 
   mediawatch.feed.admin.feed:
      class: Mediawatch\AdminBundle\Admin\FeedAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_feed, label: Feed }
      arguments: [null, Mediawatch\MediaBundle\Entity\Feed, null] 
   mediawatch.feed.admin.feedtype:
      class: Mediawatch\AdminBundle\Admin\FeedtypeAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_feed, label: Feedtype }
      arguments: [null, Mediawatch\MediaBundle\Entity\Feedtype, null]    
   mediawatch.media.admin.media:
      class: Mediawatch\AdminBundle\Admin\MediaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_media, label: Media }
      arguments: [null, Mediawatch\MediaBundle\Entity\Media, MediawatchAdminBundle:MediaAdmin]
      calls:
        - [ addChild, ['@mediawatch.common.admin.mediatag' ]]
        - [ addChild, ['@mediawatch.common.admin.mediaspeaker' ]]
        - [ addChild, ['@mediawatch.common.admin.medialanguagecategory']]
   mediawatch.media.admin.speaker:
      class: Mediawatch\AdminBundle\Admin\SpeakerAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_media, label: Speaker }
      arguments: [null, Mediawatch\MediaBundle\Entity\Speaker, null]
   mediawatch.media.admin.comment:
      class: Mediawatch\AdminBundle\Admin\CommentAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_media, label: Comment }
      arguments: [null, Mediawatch\MediaBundle\Entity\Comment, null]
   mediawatch.media.admin.contribution:
      class: Mediawatch\AdminBundle\Admin\ContributionAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_media, label: Contribution }
      arguments: [null, Mediawatch\MediaBundle\Entity\Contribution, null]   
   sonata.user.admin:
      class: Sonata\UserBundle\Admin\Entity\UserAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: mediawatch_user, label: User }
      arguments: [null, Sonata\UserBundle\Entity\User, null]  

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
      group_class: Application\Sonata\UserBundle\Entity\Group

parameters:
    home_lists_max:  6
    search_results_page: 10
    api_items_per_page: 10

ewz_recaptcha:
    public_key:   6LcAINESAAAAAC1V_QhiarIfD-ikLaLqnmAayo_0
    private_key:  6LcAINESAAAAAEvnZPMdtyBQ9YwPb3HyS5V90ie2
    secure:       false
    locale_key:   kernel.default_locale

fkr_simple_pie:
    cache_enabled: false
    cache_dir: %kernel.cache_dir%/rss
    cache_duration: 3600

fos_rest:
    view:
        view_response_listener: false
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
        formats:
            json: true
    format_listener:
        rules:
            -prefer_extension: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
